### ISSUE TITLE
Cannot send image

### ISSUE THREAD

**Issue by lijiarui** [botorange/wechaty-puppet-padplus#10]
We don't have this api right now.

**Comment by lijiarui** [comment]
Call back error:

```
(node:24556) UnhandledPromiseRejectionWarning: TypeError: callback is not a function
    at GrpcGateway.<anonymous> (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/dist/src/server-manager/grpc-gateway.js:155:25)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/dist/src/server-manager/grpc-gateway.js:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:24556) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:24556) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:24556) UnhandledPromiseRejectionWarning: Error: can not get contact info from cache manager
    at PadplusManager.<anonymous> (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/dist/src/padplus-manager/padplus-manager.js:445:23)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/dist/src/padplus-manager/padplus-manager.js:5:58)
(node:24556) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
```

**Comment by lijiarui** [comment]
fix
