### ISSUE TITLE
Accept Friend Request cannot work as expect 

### ISSUE THREAD

**Issue by lijiarui** [botorange/wechaty-puppet-padplus#11]
Run https://github.com/wechaty/wechaty-getting-started/blob/master/examples/advanced/demo-in-tutorial.js

```ts
bot.on('friendship', async function (friendship) {
  console.log(`get FRIENDSHIP event!`)

  switch (friendship.type()) {
    case this.Friendship.Type.Receive:
      await friendship.accept()
      console.log(`accept friendship!`)
      break
    case this.Friendship.Type.Confirm:
      friendship.contact().say(`Nice to meet you~`)
      break
  }
})
```

Cannot receive friendship event.

Didn't implement the method:

```
(node:20263) UnhandledPromiseRejectionWarning: Error: Method not implemented.
    at PuppetPadplus.friendshipRawPayload (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/dist/src/puppet-padplus.js:278:15)
    at PuppetPadplus.<anonymous> (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet/dist/src/puppet.js:447:43)
    at Generator.next (<anonymous>)
    at /Users/jiaruili/git/padplus/node_modules/wechaty-puppet/dist/src/puppet.js:25:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet/dist/src/puppet.js:21:12)
    at PuppetPadplus.friendshipPayload (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet/dist/src/puppet.js:432:16)
    at AnotherOriginalClass.<anonymous> (/Users/jiaruili/git/padplus/node_modules/wechaty/dist/src/user/friendship.js:128:46)
    at Generator.next (<anonymous>)
    at /Users/jiaruili/git/padplus/node_modules/wechaty/dist/src/user/friendship.js:26:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/jiaruili/git/padplus/node_modules/wechaty/dist/src/user/friendship.js:22:12)
    at AnotherOriginalClass.ready (/Users/jiaruili/git/padplus/node_modules/wechaty/dist/src/user/friendship.js:124:16)
    at Wechaty.<anonymous> (/Users/jiaruili/git/padplus/node_modules/wechaty/dist/src/wechaty.js:451:42)
    at Generator.next (<anonymous>)
    at /Users/jiaruili/git/padplus/node_modules/wechaty/dist/src/wechaty.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/jiaruili/git/padplus/node_modules/wechaty/dist/src/wechaty.js:3:12)
    at PuppetPadplus.puppet.on (/Users/jiaruili/git/padplus/node_modules/wechaty/dist/src/wechaty.js:449:63)
    at PuppetPadplus.emit (events.js:182:13)
    at PuppetPadplus.EventEmitter.emit (domain.js:442:20)
    at PuppetPadplus.emit (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet/dist/src/puppet.js:160:22)
    at PuppetPadplus.<anonymous> (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/dist/src/puppet-padplus.js:259:22)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/dist/src/puppet-padplus.js:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:20263) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:20263) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:20263) UnhandledPromiseRejectionWarning: Error: unsupported type: VerifyMsg(37)
    at Object.messageType (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/dist/src/pure-function-helpers/message-type.js:50:19)
    at Object.<anonymous> (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/dist/src/pure-function-helpers/message-raw-payload-parser.js:28:37)
    at Generator.next (<anonymous>)
    at /Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/dist/src/pure-function-helpers/message-raw-payload-parser.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/dist/src/pure-function-helpers/message-raw-payload-parser.js:4:12)
    at Object.messageRawPayloadParser (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/dist/src/pure-function-helpers/message-raw-payload-parser.js:23:12)
    at PuppetPadplus.<anonymous> (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/dist/src/puppet-padplus.js:393:59)
    at Generator.next (<anonymous>)
    at /Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/dist/src/puppet-padplus.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/dist/src/puppet-padplus.js:4:12)
    at PuppetPadplus.messageRawPayloadParser (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/dist/src/puppet-padplus.js:391:16)
    at PuppetPadplus.<anonymous> (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet/dist/src/puppet.js:490:40)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet/dist/src/puppet.js:22:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:20263) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
(node:20263) UnhandledPromiseRejectionWarning: Error: has no room for roomId:22718049432@chatroom
    at PadplusManager.<anonymous> (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/dist/src/padplus-manager/padplus-manager.js:497:19)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/dist/src/padplus-manager/padplus-manager.js:5:58)
(node:20263) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 7)
(node:20263) UnhandledPromiseRejectionWarning: Error: has no room for roomId:22718049432@chatroom
    at PadplusManager.<anonymous> (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/dist/src/padplus-manager/padplus-manager.js:497:19)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/dist/src/padplus-manager/padplus-manager.js:5:58)
(node:20263) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 9)
```

**Comment by iguxiaobei** [comment]
resoved.

**Comment by lijiarui** [comment]
Still has error:

```
(node:35164) UnhandledPromiseRejectionWarning: Error: unsupported type: VerifyMsg(37)
    at Object.messageType (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/dist/src/pure-function-helpers/message-type.js:50:19)
    at Object.<anonymous> (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/dist/src/pure-function-helpers/message-raw-payload-parser.js:28:37)
    at Generator.next (<anonymous>)
    at /Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/dist/src/pure-function-helpers/message-raw-payload-parser.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/dist/src/pure-function-helpers/message-raw-payload-parser.js:4:12)
    at Object.messageRawPayloadParser (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/dist/src/pure-function-helpers/message-raw-payload-parser.js:23:12)
    at PuppetPadplus.<anonymous> (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/dist/src/puppet-padplus.js:413:59)
    at Generator.next (<anonymous>)
    at /Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/dist/src/puppet-padplus.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/dist/src/puppet-padplus.js:4:12)
    at PuppetPadplus.messageRawPayloadParser (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/dist/src/puppet-padplus.js:411:16)
    at PuppetPadplus.<anonymous> (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet/dist/src/puppet.js:490:40)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet/dist/src/puppet.js:22:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:35164) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:35164) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by lijiarui** [comment]
fix
