### ISSUE TITLE
[PuppetPadplus.messageFile Error]Receive Audio/Image ---> method not implement

### ISSUE THREAD

**Issue by lijiarui** [botorange/wechaty-puppet-padplus#13]
Reproduce code:

`advanced/media-file-bot.js`

```ts
async function onMessage(msg) {
  console.log(`RECV: ${msg}`)

  if (msg.type() !== Message.Type.Text) {
    console.log('Message Type is not Text')
    const file = await msg.toFileBox()
    const name = file.name
    console.log('Save file to: ' + name)
    file.toFile(name)
  }
}
```

error log:

```shell
RECV: Message#Audio[🗣Contact<李佳芮>]
Message Type is not Text
(node:25657) UnhandledPromiseRejectionWarning: Error: Method not implemented.
    at PuppetPadplus.messageFile (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/dist/src/puppet-padplus.js:311:15)
    at AnotherOriginalClass.<anonymous> (/Users/jiaruili/git/padplus/node_modules/wechaty/dist/src/user/message.js:764:47)
    at Generator.next (<anonymous>)
    at /Users/jiaruili/git/padplus/node_modules/wechaty/dist/src/user/message.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/jiaruili/git/padplus/node_modules/wechaty/dist/src/user/message.js:3:12)
    at AnotherOriginalClass.toFileBox (/Users/jiaruili/git/padplus/node_modules/wechaty/dist/src/user/message.js:760:16)
    at Wechaty.onMessage (/Users/jiaruili/git/padplus/examples/advanced/media-file-bot.js:66:28)
    at Wechaty.on.args (/Users/jiaruili/git/padplus/node_modules/wechaty/dist/src/wechaty.js:384:26)
    at Wechaty.emit (events.js:182:13)
    at Wechaty.EventEmitter.emit (domain.js:442:20)
    at Wechaty.emit (/Users/jiaruili/git/padplus/node_modules/wechaty/dist/src/wechaty.js:180:22)
    at Wechaty.<anonymous> (/Users/jiaruili/git/padplus/node_modules/wechaty/dist/src/wechaty.js:477:30)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/jiaruili/git/padplus/node_modules/wechaty/dist/src/wechaty.js:4:58)
(node:25657) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:25657) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by windmemory** [comment]
done
