### ISSUE TITLE
[Room] When a bot invite someone in the room ,get error

### ISSUE THREAD

**Issue by lijiarui** [botorange/wechaty-puppet-padplus#14]
## Reproduce

Bot invite A join the room, then get the following error:

```
(node:25991) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'name' of null
    at Wechaty.<anonymous> (/Users/jiaruili/git/padplus/examples/advanced/demo-in-tutorial.js:62:52)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:25991) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)

```

**Comment by lijiarui** [comment]
change to another error:

```shell

22:41:56 ERR GRPC_GATEWAY Error: 13 INTERNAL: Failed to parse server response
    at Object.exports.createStatusError (/Users/jiaruili/git/padplus/node_modules/grpc/src/common.js:91:15)
    at ClientReadableStream._emitStatusIfDone (/Users/jiaruili/git/padplus/node_modules/grpc/src/client.js:233:26)
    at ClientReadableStream._receiveStatus (/Users/jiaruili/git/padplus/node_modules/grpc/src/client.js:211:8)
    at Object.onReceiveStatus (/Users/jiaruili/git/padplus/node_modules/grpc/src/client_interceptors.js:1272:15)
    at InterceptingListener._callNext (/Users/jiaruili/git/padplus/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/Users/jiaruili/git/padplus/node_modules/grpc/src/client_interceptors.js:618:8)
    at /Users/jiaruili/git/padplus/node_modules/grpc/src/client_interceptors.js:1029:24
```

**Comment by lijiarui** [comment]
fix, and what I paste above maybe another error, see #21
