### ISSUE TITLE
Invite others into the room --- > method not implement

### ISSUE THREAD

**Issue by lijiarui** [botorange/wechaty-puppet-padplus#15]
## reproduce

bot use `add()` to invite A into the group

log as follows:

```shell
(node:25991) UnhandledPromiseRejectionWarning: Error: Method not implemented.
    at PuppetPadplus.roomAdd (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/dist/src/puppet-padplus.js:566:15)
    at AnotherOriginalClass.<anonymous> (/Users/jiaruili/git/padplus/node_modules/wechaty/dist/src/user/room.js:575:31)
    at Generator.next (<anonymous>)
    at /Users/jiaruili/git/padplus/node_modules/wechaty/dist/src/user/room.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/jiaruili/git/padplus/node_modules/wechaty/dist/src/user/room.js:3:12)
    at AnotherOriginalClass.add (/Users/jiaruili/git/padplus/node_modules/wechaty/dist/src/user/room.js:573:16)
    at Wechaty.<anonymous> (/Users/jiaruili/git/padplus/examples/advanced/demo-in-tutorial.js:76:21)
(node:25991) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 17)
```

**Comment by lijiarui** [comment]
fix
