### ISSUE TITLE
[Room] Error: no inviterId found

### ISSUE THREAD

**Issue by lijiarui** [botorange/wechaty-puppet-padplus#17]
```
(node:35513) UnhandledPromiseRejectionWarning: Error: no inviterId found
    at PuppetPadplus.<anonymous> (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/dist/src/puppet-padplus.js:453:27)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/dist/src/puppet-padplus.js:5:58)
(node:35513) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 8)
(node:35513) UnhandledPromiseRejectionWarning: Error: can not get contact info from cache manager
    at PadplusManager.<anonymous> (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/dist/src/padplus-manager/padplus-manager.js:428:23)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/dist/src/padplus-manager/padplus-manager.js:5:58)
(node:35513) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 10)
22:17:07 ERR GRPC_GATEWAY Error: 13 INTERNAL: Failed to parse server response
    at Object.exports.createStatusError (/Users/jiaruili/git/padplus/node_modules/grpc/src/common.js:91:15)
    at ClientReadableStream._emitStatusIfDone (/Users/jiaruili/git/padplus/node_modules/grpc/src/client.js:233:26)
    at ClientReadableStream._receiveStatus (/Users/jiaruili/git/padplus/node_modules/grpc/src/client.js:211:8)
    at Object.onReceiveStatus (/Users/jiaruili/git/padplus/node_modules/grpc/src/client_interceptors.js:1272:15)
    at InterceptingListener._callNext (/Users/jiaruili/git/padplus/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/Users/jiaruili/git/padplus/node_modules/grpc/src/client_interceptors.js:618:8)
    at /Users/jiaruili/git/padplus/node_modules/grpc/src/client_interceptors.js:1029:24
```

**Comment by windmemory** [comment]
Could you please provide reproduce steps?
