### ISSUE TITLE
login error

### ISSUE THREAD

**Issue by lijiarui** [botorange/wechaty-puppet-padplus#2]
After I scan the qrcode, I login successfully(Mobile show I login with ipad), but get the following error saying login error:

```shell
  padplus ts-node test.ts
11:32:30 INFO Wechaty <Puppet#0<PuppetPadplus>()>() start() v0.28.3 is starting...
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█ ▄▄▄▄▄ █ ▄▄ █ ▀█ ▀ █▄█ ▄▄▄▄▄ █
█ █   █ ██▄█▀▀▄ ▀█ ▀  █ █   █ █
█ █▄▄▄█ █ ▀▀▄ ▄▀▄▀  █▀█ █▄▄▄█ █
█▄▄▄▄▄▄▄█ ▀▄█▄█▄▀▄█ ▀ █▄▄▄▄▄▄▄█
█  ▄█▀ ▄▀ ▄█▄ █ ▄▀██▀▄▄  ▄██  █
█▄▀▄█▀ ▄▄▄▄ ▀ █▀ ▀▄ ▄▀█▀█ ▄▄█▄█
█ ▀▀   ▄▄ ▄ ███▀ ▀▀ ▀ ▄  ██▀▀ █
█▄  ▄ ▄▄▀ ▄ ▄███▄█▄▄ ▀█▀▄ ▄██▄█
██▄▀▀▄ ▄▀▀ █▄ █▀ ▀ █▀ ▀ ▀█ ▀▀ █
█▄▄ ▀  ▄█ ▀ ▀ ▄▀ ▄█▀ █ ▄█ ███▄█
█▄▄█▄█▄▄▄▀ ███▄█▀ ▀▀▄ ▄▄▄  ▀▄▀█
█ ▄▄▄▄▄ █▀█ ▄██▄ ▄▄ ▀ █▄█ ▀█▀ █
█ █   █ ██ ▀▄ ▀██▀▀ ▄  ▄▄ ▀█▄▀█
█ █▄▄▄█ █  █▀ ▄█▄█▄ █▀██▀▄▀█▄▄█
█▄▄▄▄▄▄▄█▄▄██▄▄▄▄██▄▄▄█▄█▄▄██▄█

11:32:36 INFO PadplusManager
            =================================================
            QRCODE_SCAN MSG : 已确认
            =================================================

(node:10158) UnhandledPromiseRejectionWarning: Error: bot not login.
    at PuppetPadplus.<anonymous> (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/src/puppet-padplus.ts:217:13)
    at Generator.next (<anonymous>)
    at /Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/dist/src/puppet-padplus.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/dist/src/puppet-padplus.js:4:12)
    at PuppetPadplus.contactRawPayload (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/dist/src/puppet-padplus.js:187:16)
    at PuppetPadplus.<anonymous> (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet/src/puppet.ts:678:35)
    at Generator.next (<anonymous>)
    at /Users/jiaruili/git/padplus/node_modules/wechaty-puppet/dist/src/puppet.js:25:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet/dist/src/puppet.js:21:12)
    at PuppetPadplus.contactPayload (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet/dist/src/puppet.js:389:16)
    at AnotherOriginalClass.<anonymous> (/Users/jiaruili/git/padplus/node_modules/wechaty/src/user/contact.ts:695:40)
    at Generator.next (<anonymous>)
    at /Users/jiaruili/git/padplus/node_modules/wechaty/dist/src/user/contact.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/jiaruili/git/padplus/node_modules/wechaty/dist/src/user/contact.js:3:12)
    at AnotherOriginalClass.ready (/Users/jiaruili/git/padplus/node_modules/wechaty/dist/src/user/contact.js:584:16)
    at Wechaty.<anonymous> (/Users/jiaruili/git/padplus/node_modules/wechaty/src/wechaty.ts:641:27)
    at Generator.next (<anonymous>)
    at /Users/jiaruili/git/padplus/node_modules/wechaty/dist/src/wechaty.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/jiaruili/git/padplus/node_modules/wechaty/dist/src/wechaty.js:3:12)
    at PuppetPadplus.puppet.on (/Users/jiaruili/git/padplus/node_modules/wechaty/src/wechaty.ts:639:48)
    at PuppetPadplus.emit (events.js:182:13)
    at PuppetPadplus.EventEmitter.emit (domain.js:442:20)
    at PuppetPadplus.emit (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet/src/puppet.ts:282:18)
    at PuppetPadplus.<anonymous> (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/src/puppet-padplus.ts:85:12)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/dist/src/puppet-padplus.js:5:58)
(node:10158) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:10158) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by su-chang** [comment]
已解决
