### ISSUE TITLE
[Room] Error: can not get room info by api

### ISSUE THREAD

**Issue by lijiarui** [botorange/wechaty-puppet-padplus#20]
```
(node:36409) UnhandledPromiseRejectionWarning: Error: can not get room info by api
    at PadplusManager.<anonymous> (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/dist/src/padplus-manager/padplus-manager.js:478:23)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/dist/src/padplus-manager/padplus-manager.js:5:58)
(node:36409) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:36409) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:36409) UnhandledPromiseRejectionWarning: Error: can not get contact info from cache manager
    at PadplusManager.<anonymous> (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/dist/src/padplus-manager/padplus-manager.js:428:23)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/dist/src/padplus-manager/padplus-manager.js:5:58)
(node:36409) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
```

**Comment by su-chang** [comment]
查询群组信息时，如果缓存中不存在，则需要发起请求查询

请求发起成功后，等待回调存入缓存，轮询查询缓存

设置默认轮询间隔及次数，若超出，抛出异常

**Comment by windmemory** [comment]
should be done.
