### ISSUE TITLE
Cannot get Image Callback

### ISSUE THREAD

**Issue by lijiarui** [botorange/wechaty-puppet-padplus#22]
## reproduce:
```ts
  /**
   * 1. reply 'dong'
   */
  await msg.say('dong')
  console.log('REPLY: dong')

  /**
   * 2. reply image(qrcode image)
   */
  const fileBox = FileBox.fromUrl('https://chatie.io/wechaty/images/bot-qr-code.png')
  await msg.say(fileBox)
  console.log('REPLY: %s', fileBox.toString())

  /**
   * 3. reply 'scan now!'
   */
  await msg.say([
    'Join Wechaty Developers Community\n\n',
    'Scan now, because other Wechaty developers want to talk with you too!\n\n',
    '(secret code: wechaty)',
  ].join(''))
```
But I only get the first 2 say, log as follows:

```
Message#Text[🗣Contact<wechaty bot>]	ding
REPLY: dong
Get file box

(node:43510) UnhandledPromiseRejectionWarning: Error: request timeout
    at Timeout.setTimeout [as _onTimeout] (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/dist/src/server-manager/grpc-gateway.js:85:65)
    at ontimeout (timers.js:425:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
(node:43510) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:43510) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by windmemory** [comment]
should be ok.
