### ISSUE TITLE
join room can not get room-join event

### ISSUE THREAD

**Issue by lijiarui** [botorange/wechaty-puppet-padplus#23]
When A invite B join the room, it will get the following error:

```
room.on(join) id: 19118881677@chatroom
02:25:41 INFO Bot EVENT: room-join - Room "dingRoom" got new member "", invited by "wechaty bot"
bot room-join room id: 19118881677@chatroom
02:25:41 INFO Bot checkRoomJoin("dingRoom", "", "wechaty bot")
(node:43770) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'id' of undefined
    at AnotherOriginalClass.<anonymous> (/Users/jiaruili/git/padplus/node_modules/wechaty/dist/src/user/room.js:771:88)
    at Generator.next (<anonymous>)
    at /Users/jiaruili/git/padplus/node_modules/wechaty/dist/src/user/room.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/jiaruili/git/padplus/node_modules/wechaty/dist/src/user/room.js:3:12)
    at AnotherOriginalClass.alias (/Users/jiaruili/git/padplus/node_modules/wechaty/dist/src/user/room.js:770:16)
    at AnotherOriginalClass.<anonymous> (/Users/jiaruili/git/padplus/node_modules/wechaty/dist/src/user/room.js:384:162)
    at Generator.next (<anonymous>)
    at /Users/jiaruili/git/padplus/node_modules/wechaty/dist/src/user/room.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/jiaruili/git/padplus/node_modules/wechaty/dist/src/user/room.js:3:12)
    at Promise.all.mentionList.map (/Users/jiaruili/git/padplus/node_modules/wechaty/dist/src/user/room.js:384:89)
    at Array.map (<anonymous>)
    at AnotherOriginalClass.<anonymous> (/Users/jiaruili/git/padplus/node_modules/wechaty/dist/src/user/room.js:384:72)
    at Generator.next (<anonymous>)
    at /Users/jiaruili/git/padplus/node_modules/wechaty/dist/src/user/room.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/jiaruili/git/padplus/node_modules/wechaty/dist/src/user/room.js:3:12)
    at AnotherOriginalClass.say (/Users/jiaruili/git/padplus/node_modules/wechaty/dist/src/user/room.js:378:16)
    at Wechaty.<anonymous> (/Users/jiaruili/git/padplus/examples/advanced/room-bot.js:138:14)
(node:43770) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
02:25:51 ERR Bot checkRoomJoin() exception: Error: no id
    at PuppetPadplus.<anonymous> (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet/dist/src/puppet.js:732:23)
    at Generator.next (<anonymous>)
    at /Users/jiaruili/git/padplus/node_modules/wechaty-puppet/dist/src/puppet.js:25:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet/dist/src/puppet.js:21:12)
    at PuppetPadplus.roomMemberPayload (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet/dist/src/puppet.js:729:16)
    at AnotherOriginalClass.<anonymous> (/Users/jiaruili/git/padplus/node_modules/wechaty/dist/src/user/room.js:771:53)
    at Generator.next (<anonymous>)
    at /Users/jiaruili/git/padplus/node_modules/wechaty/dist/src/user/room.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/jiaruili/git/padplus/node_modules/wechaty/dist/src/user/room.js:3:12)
    at AnotherOriginalClass.alias (/Users/jiaruili/git/padplus/node_modules/wechaty/dist/src/user/room.js:770:16)
    at AnotherOriginalClass.<anonymous> (/Users/jiaruili/git/padplus/node_modules/wechaty/dist/src/user/room.js:384:162)
    at Generator.next (<anonymous>)
    at /Users/jiaruili/git/padplus/node_modules/wechaty/dist/src/user/room.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/jiaruili/git/padplus/node_modules/wechaty/dist/src/user/room.js:3:12)
    at Promise.all.mentionList.map (/Users/jiaruili/git/padplus/node_modules/wechaty/dist/src/user/room.js:384:89)
    at Array.map (<anonymous>)
    at AnotherOriginalClass.<anonymous> (/Users/jiaruili/git/padplus/node_modules/wechaty/dist/src/user/room.js:384:72)
    at Generator.next (<anonymous>)
    at /Users/jiaruili/git/padplus/node_modules/wechaty/dist/src/user/room.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/jiaruili/git/padplus/node_modules/wechaty/dist/src/user/room.js:3:12)
    at AnotherOriginalClass.say (/Users/jiaruili/git/padplus/node_modules/wechaty/dist/src/user/room.js:378:16)
    at AnotherOriginalClass.checkRoomJoin (/Users/jiaruili/git/padplus/examples/advanced/room-bot.js:355:18)

```

**Comment by lijiarui** [comment]
Due to this,  when someone enters the group, they cannot receive the `入群欢迎语`

**Comment by windmemory** [comment]
should be okay
