### ISSUE TITLE
Server stuck after create room

### ISSUE THREAD

**Issue by CooperFu** [botorange/wechaty-puppet-padplus#31]
```
2019-09-23 14:26 +08:00: app listening on port 3034!
2019-09-23 14:26 +08:00: 14:26:32 INFO Wechaty <Puppet#0<PuppetPadplus>()>(wuerxiaomishu) start() v0.28.3 is starting...
2019-09-23 14:26 +08:00: 无二之旅-小秘书6 unibot_login
2019-09-23 14:28 +08:00: start--------------- 17600904964
2019-09-23 14:28 +08:00: end--------------- {"avatar":"http://wx.qlogo.cn/mmhead/ver_1/dw02mZIbhZRfEBkmKorHuyJUVMeEJzAJiatXIKgp55U7kvgX65mpoTmNibLLmdhgKcfFx39N4Fx5iaFWw3XgViaHHVxodNGu49HsRvyetFHfg1Y/132","v1":"v1_85c75be112b129689c5d54b4be5a6fa046f0d723bbf329be0a8b0cacbfabb55736485b2c92bb0a872dde94547c957499@stranger","v2":"v2_6d2930edec26d97faa138ba9949109ddd7e6447637751fbebf537339492542296d0f0fa338ccd9c65cbc4c0d26ef24eb@stranger","searchId":"17600904964","nickName":"aa刘波","wxid":"wxid6020870207312","message":"Everything is OK","status":"0"}
2019-09-23 14:40 +08:00: start--------------- 17600904964
2019-09-23 14:40 +08:00: end--------------- {"avatar":"http://wx.qlogo.cn/mmhead/ver_1/dw02mZIbhZRfEBkmKorHuyJUVMeEJzAJiatXIKgp55U7kvgX65mpoTmNibLLmdhgKcfFx39N4Fx5iaFWw3XgViaHHVxodNGu49HsRvyetFHfg1Y/132","v1":"v1_85c75be112b129689c5d54b4be5a6fa046f0d723bbf329be0a8b0cacbfabb55736485b2c92bb0a872dde94547c957499@stranger","v2":"v2_6d2930edec26d97faa138ba9949109dd04c85f52b413b1b96be31210b6ee689a9739f586135eacc9181c94daf415a9b8@stranger","searchId":"17600904964","nickName":"aa刘波","wxid":"wxid6020870207312","message":"Everything is OK","status":"0"}


2019-09-23 14:51 +08:00: aaaaaaaaa wxid_6020870207312 fqaizmm 261647-测试-服务群
2019-09-23 14:51 +08:00: [ Contact {
2019-09-23 14:51 +08:00:     domain: null,
2019-09-23 14:51 +08:00:     _events: [Object: null prototype] {},
2019-09-23 14:51 +08:00:     _eventsCount: 0,
2019-09-23 14:51 +08:00:     _maxListeners: undefined,
2019-09-23 14:51 +08:00:     id: 'wxid_6020870207312',
2019-09-23 14:51 +08:00:     payload:
2019-09-23 14:51 +08:00:      { alias: '',
2019-09-23 14:51 +08:00:        avatar:
2019-09-23 14:51 +08:00:         'http://wx.qlogo.cn/mmhead/ver_1/XYjnD0hiaoSh2yUz5AicsGnanShNFlugKM0FlLroRL5Ffr3YLv6mlB4YoIKmNdibbOkTPz6bkm5K1Y0szkKFPQxOSf3GKNrulMgatgdZpm2vWY/0',
2019-09-23 14:51 +08:00:        city: '',
2019-09-23 14:51 +08:00:        friend: true,
2019-09-23 14:51 +08:00:        gender: 1,
2019-09-23 14:51 +08:00:        id: 'wxid_6020870207312',
2019-09-23 14:51 +08:00:        name: 'aa刘波',
2019-09-23 14:51 +08:00:        province: '',
2019-09-23 14:51 +08:00:        signature: '',
2019-09-23 14:51 +08:00:        type: 1,
2019-09-23 14:51 +08:00:        weixin: 'wxid_6020870207312' },
2019-09-23 14:51 +08:00:     [Symbol(name)]: 'Contact',
2019-09-23 14:51 +08:00:     [Symbol(counter)]: 18 },
2019-09-23 14:51 +08:00:   Contact {
2019-09-23 14:51 +08:00:     domain: null,
2019-09-23 14:51 +08:00:     _events: [Object: null prototype] {},
2019-09-23 14:51 +08:00:     _eventsCount: 0,
2019-09-23 14:51 +08:00:     _maxListeners: undefined,
2019-09-23 14:51 +08:00:     id: 'fqaizmm',
2019-09-23 14:51 +08:00:     payload:
2019-09-23 14:51 +08:00:      { alias: '',
2019-09-23 14:51 +08:00:        avatar:
2019-09-23 14:51 +08:00:         'http://wx.qlogo.cn/mmhead/ver_1/HDVPbQ5KKQXX5QIpxUeHE30rB2ooRIuYULDytyk7jH0RHasHxumCxCHIjiaEnYIhB57U1ZRRwORyyzSGaywQYlw/132',
2019-09-23 14:51 +08:00:        city: 'Chaoyang',
2019-09-23 14:51 +08:00:        friend: true,
2019-09-23 14:51 +08:00:        gender: 1,
2019-09-23 14:51 +08:00:        id: 'fqaizmm',
2019-09-23 14:51 +08:00:        name: '付强',
2019-09-23 14:51 +08:00:        province: 'Beijing',
2019-09-23 14:51 +08:00:        signature: '',
2019-09-23 14:51 +08:00:        type: 1,
2019-09-23 14:51 +08:00:        weixin: 'fqaizmm' },
2019-09-23 14:51 +08:00:     [Symbol(name)]: 'Contact',
2019-09-23 14:51 +08:00:     [Symbol(counter)]: 30 } ]
2019-09-23 14:51 +08:00: { status: 'success',
2019-09-23 14:51 +08:00:   message: '创建群聊成功',
2019-09-23 14:51 +08:00:   room_id: '23901740694@chatroom' }


2019-09-23 14:56 +08:00: Error: request timeout
2019-09-23 14:56 +08:00:     at Timeout.setTimeout [as _onTimeout] (/home/deploy/wechaty_padplus/source/node_modules/wechaty-puppet-padplus/dist/src/server-manager/grpc-gateway.js:116:69)
2019-09-23 14:56 +08:00:     at ontimeout (timers.js:436:11)
2019-09-23 14:56 +08:00:     at tryOnTimeout (timers.js:300:5)
2019-09-23 14:56 +08:00:     at listOnTimeout (timers.js:263:5)
2019-09-23 14:56 +08:00:     at Timer.processTimers (timers.js:223:10)
```

**Comment by su-chang** [comment]
用新版本重新试下，看看能否复现该问题。我这边暂时未能复现此问题。
