### ISSUE TITLE
puppet npm module not supported: "Puppet#0<PuppetPadplus>()"

### ISSUE THREAD

**Issue by PandaTsui** [botorange/wechaty-puppet-padplus#41]
> Important：Please file the issue follow the template, or we won't help you to solve the problem.

## 0. Report Issue Guide

1. Please run the following command and check whether the problem has been fixed：

```
npm install wechaty-puppet-padlus@next
```

2. Please search in the issue first, and make sure your problem had not been reported before

## 1. Versions

- What is your wechaty version?
Answer: 0.29.2

- What is your wechaty-puppet-padplus version?
Answer: 0.0.124

- What is your node version? (run `node --version`)
Answer: v10.16.0

- What os are you using
Answer:Ubuntu 16.04.4 LTS

## 2. Describe the bug

使用padplush协议启动，调用login方法后，停顿3秒报错

## 4. Expected behavior
希望能正常登录，并返回二维码

## 5. Actual behavior

If applicable, add screenshots to help explain your problem. But do not paste log screenshots here.

## 6. Full Output Logs

Set env `WECHATY_LOG=silly` in order to set log level to silly, then we can get the full log (If you dosen't set log env, log level is info as default, we cannot get the full log)

**We need full log instead of log screenshot or log fragments!**

<details>
<summary>

</summary>

```
0|wechat | 2019-10-10 13:50 +08:00: Error: 
0|wechat | puppet npm module not supported: "Puppet#0<PuppetPadplus>()"
0|wechat | learn more about supported Wechaty Puppet from our directory at
0|wechat | <https://github.com/Chatie/wechaty-puppet/wiki/Directory>
0|wechat |     at Function.<anonymous> (/home/wwwroot/wechat-monitor/node_modules/wechaty/dist/src/puppet-manager.js:77:31)
0|wechat |     at Generator.next (<anonymous>)
0|wechat |     at /home/wwwroot/wechat-monitor/node_modules/wechaty/dist/src/puppet-manager.js:7:71
0|wechat |     at new Promise (<anonymous>)
0|wechat |     at __awaiter (/home/wwwroot/wechat-monitor/node_modules/wechaty/dist/src/puppet-manager.js:3:12)
0|wechat |     at Function.resolveName (/home/wwwroot/wechat-monitor/node_modules/wechaty/dist/src/puppet-manager.js:57:16)
0|wechat |     at Function.<anonymous> (/home/wwwroot/wechat-monitor/node_modules/wechaty/dist/src/puppet-manager.js:39:45)
0|wechat |     at Generator.next (<anonymous>)
0|wechat |     at /home/wwwroot/wechat-monitor/node_modules/wechaty/dist/src/puppet-manager.js:7:71
0|wechat |     at new Promise (<anonymous>)
0|wechat |     at __awaiter (/home/wwwroot/wechat-monitor/node_modules/wechaty/dist/src/puppet-manager.js:3:12)
0|wechat |     at Function.resolve (/home/wwwroot/wechat-monitor/node_modules/wechaty/dist/src/puppet-manager.js:32:16)
0|wechat |     at Wechaty.<anonymous> (/home/wwwroot/wechat-monitor/node_modules/wechaty/dist/src/wechaty.js:411:73)
0|wechat |     at Generator.next (<anonymous>)
0|wechat |     at /home/wwwroot/wechat-monitor/node_modules/wechaty/dist/src/wechaty.js:7:71
0|wechat |     at new Promise (<anonymous>)
0|wechat |     at __awaiter (/home/wwwroot/wechat-monitor/node_modules/wechaty/dist/src/wechaty.js:3:12)
0|wechat |     at Wechaty.initPuppet (/home/wwwroot/wechat-monitor/node_modules/wechaty/dist/src/wechaty.js:393:16)
0|wechat |     at Wechaty.<anonymous> (/home/wwwroot/wechat-monitor/node_modules/wechaty/dist/src/wechaty.js:619:28)
0|wechat |     at Generator.next (<anonymous>)
0|wechat |     at fulfilled (/home/wwwroot/wechat-monitor/node_modules/wechaty/dist/src/wechaty.js:4:58)
0|wechat |     at process._tickCallback (internal/process/next_tick.js:68:7)
0|wechat |     at Function.Module.runMain (internal/modules/cjs/loader.js:832:11)
0|wechat |     at startup (internal/bootstrap/node.js:283:19)
0|wechat |     at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
0|wechat | 2019-10-10 13:50 +08:00: 13:50:34 ERR Wechaty start() exception: 
0|wechat | puppet npm module not supported: "Puppet#0<PuppetPadplus>()"
0|wechat | learn more about supported Wechaty Puppet from our directory at
0|wechat | <https://github.com/Chatie/wechaty-puppet/wiki/Directory>
0|wechat | 2019-10-10 13:50 +08:00: on-error Error: 
0|wechat | puppet npm module not supported: "Puppet#0<PuppetPadplus>()"
0|wechat | learn more about supported Wechaty Puppet from our directory at
0|wechat | <https://github.com/Chatie/wechaty-puppet/wiki/Directory>
0|wechat |     at Function.<anonymous> (/home/wwwroot/wechat-monitor/node_modules/wechaty/dist/src/puppet-manager.js:77:31)
0|wechat |     at Generator.next (<anonymous>)
0|wechat |     at /home/wwwroot/wechat-monitor/node_modules/wechaty/dist/src/puppet-manager.js:7:71
0|wechat |     at new Promise (<anonymous>)
0|wechat |     at __awaiter (/home/wwwroot/wechat-monitor/node_modules/wechaty/dist/src/puppet-manager.js:3:12)
0|wechat |     at Function.resolveName (/home/wwwroot/wechat-monitor/node_modules/wechaty/dist/src/puppet-manager.js:57:16)
0|wechat |     at Function.<anonymous> (/home/wwwroot/wechat-monitor/node_modules/wechaty/dist/src/puppet-manager.js:39:45)
0|wechat |     at Generator.next (<anonymous>)
0|wechat |     at /home/wwwroot/wechat-monitor/node_modules/wechaty/dist/src/puppet-manager.js:7:71
0|wechat |     at new Promise (<anonymous>)
0|wechat |     at __awaiter (/home/wwwroot/wechat-monitor/node_modules/wechaty/dist/src/puppet-manager.js:3:12)
0|wechat |     at Function.resolve (/home/wwwroot/wechat-monitor/node_modules/wechaty/dist/src/puppet-manager.js:32:16)
0|wechat |     at Wechaty.<anonymous> (/home/wwwroot/wechat-monitor/node_modules/wechaty/dist/src/wechaty.js:411:73)
0|wechat |     at Generator.next (<anonymous>)
0|wechat |     at /home/wwwroot/wechat-monitor/node_modules/wechaty/dist/src/wechaty.js:7:71
0|wechat |     at new Promise (<anonymous>)
0|wechat |     at __awaiter (/home/wwwroot/wechat-monitor/node_modules/wechaty/dist/src/wechaty.js:3:12)
0|wechat |     at Wechaty.initPuppet (/home/wwwroot/wechat-monitor/node_modules/wechaty/dist/src/wechaty.js:393:16)
0|wechat |     at Wechaty.<anonymous> (/home/wwwroot/wechat-monitor/node_modules/wechaty/dist/src/wechaty.js:619:28)
0|wechat |     at Generator.next (<anonymous>)
0|wechat |     at fulfilled (/home/wwwroot/wechat-monitor/node_modules/wechaty/dist/src/wechaty.js:4:58)
0|wechat |     at process._tickCallback (internal/process/next_tick.js:68:7)
0|wechat |     at Function.Module.runMain (internal/modules/cjs/loader.js:832:11)
0|wechat |     at startup (internal/bootstrap/node.js:283:19)
0|wechat |     at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
0|wechat | 2019-10-10 13:50 +08:00: 13:50:34 INFO Wechaty <Puppet#0<PuppetPadplus>()> stop() v0.29.2 is stoping ...
0|wechat | 2019-10-10 13:50 +08:00: res undefined
0|wechat | 2019-10-10 13:50 +08:00: 13:50:34 WARN Wechaty stop() puppet.stop() exception: static puppet not found for Wechaty, please see issue #1217: https://github.com/Chatie/wechaty/issues/1217

```

</details>

[bug]
![image](https://user-images.githubusercontent.com/21979377/66542522-6463d800-eb65-11e9-9fcb-2e3d880d5ddc.png)

**Comment by PandaTsui** [comment]
因为我用的wechaty和plus的版本不对
