### ISSUE TITLE
 UnhandledPromiseRejectionWarning: Error: getContactPayload after login

### ISSUE THREAD

**Issue by lijiarui** [botorange/wechaty-puppet-padplus#5]
```
(node:15425) UnhandledPromiseRejectionWarning: Error: getContactPayload
    at PadplusManager.<anonymous> (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/src/padplus-manager/padplus-manager.ts:485:13)
    at Generator.next (<anonymous>)
    at /Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/dist/src/padplus-manager/padplus-manager.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/dist/src/padplus-manager/padplus-manager.js:4:12)
    at PadplusManager.getContactPayload (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/dist/src/padplus-manager/padplus-manager.js:404:16)
    at PuppetPadplus.<anonymous> (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/src/puppet-padplus.ts:227:40)
    at Generator.next (<anonymous>)
    at /Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/dist/src/puppet-padplus.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/dist/src/puppet-padplus.js:4:12)
    at PuppetPadplus.contactRawPayload (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/dist/src/puppet-padplus.js:196:16)
    at PuppetPadplus.<anonymous> (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet/src/puppet.ts:678:35)
    at Generator.next (<anonymous>)
    at /Users/jiaruili/git/padplus/node_modules/wechaty-puppet/dist/src/puppet.js:25:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet/dist/src/puppet.js:21:12)
    at PuppetPadplus.contactPayload (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet/dist/src/puppet.js:389:16)
    at AnotherOriginalClass.<anonymous> (/Users/jiaruili/git/padplus/node_modules/wechaty/src/user/contact.ts:695:40)
    at Generator.next (<anonymous>)
    at /Users/jiaruili/git/padplus/node_modules/wechaty/dist/src/user/contact.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/jiaruili/git/padplus/node_modules/wechaty/dist/src/user/contact.js:3:12)
    at AnotherOriginalClass.ready (/Users/jiaruili/git/padplus/node_modules/wechaty/dist/src/user/contact.js:584:16)
    at Wechaty.<anonymous> (/Users/jiaruili/git/padplus/node_modules/wechaty/src/wechaty.ts:641:27)
    at Generator.next (<anonymous>)
    at /Users/jiaruili/git/padplus/node_modules/wechaty/dist/src/wechaty.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/jiaruili/git/padplus/node_modules/wechaty/dist/src/wechaty.js:3:12)
    at PuppetPadplus.puppet.on (/Users/jiaruili/git/padplus/node_modules/wechaty/src/wechaty.ts:639:48)
    at PuppetPadplus.emit (events.js:182:13)
    at PuppetPadplus.EventEmitter.emit (domain.js:442:20)
    at PuppetPadplus.emit (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet/src/puppet.ts:282:18)
    at PuppetPadplus.<anonymous> (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet/src/puppet.ts:373:10)
    at Generator.next (<anonymous>)
    at /Users/jiaruili/git/padplus/node_modules/wechaty-puppet/dist/src/puppet.js:25:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet/dist/src/puppet.js:21:12)
    at PuppetPadplus.login (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet/dist/src/puppet.js:199:16)
    at PuppetPadplus.<anonymous> (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/src/puppet-padplus.ts:90:24)
    at Generator.next (<anonymous>)
    at /Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/dist/src/puppet-padplus.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/dist/src/puppet-padplus.js:4:12)
    at PadplusManager.manager.on (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/src/puppet-padplus.ts:88:62)
    at GrpcEventEmitter.grpcGatewayEmmiter.on.args (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/src/padplus-manager/padplus-manager.ts:147:18)
    at GrpcEventEmitter.emit (events.js:182:13)
    at GrpcEventEmitter.EventEmitter.emit (domain.js:442:20)
    at PadplusManager.emit (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/src/padplus-manager/padplus-manager.ts:132:36)
    at PadplusManager.<anonymous> (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/src/padplus-manager/padplus-manager.ts:226:18)
    at Generator.next (<anonymous>)
    at /Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/dist/src/padplus-manager/padplus-manager.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/dist/src/padplus-manager/padplus-manager.js:4:12)
    at GrpcEventEmitter.grpcGatewayEmmiter.on (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/src/padplus-manager/padplus-manager.ts:193:71)
    at GrpcEventEmitter.emit (events.js:182:13)
    at GrpcEventEmitter.EventEmitter.emit (domain.js:442:20)
    at GrpcGateway.<anonymous> (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/src/server-manager/grpc-gateway.ts:212:23)
    at Generator.next (<anonymous>)
    at /Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/dist/src/server-manager/grpc-gateway.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/dist/src/server-manager/grpc-gateway.js:4:12)
    at ClientReadableStream.result.on (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/src/server-manager/grpc-gateway.ts:180:56)
    at ClientReadableStream.emit (events.js:182:13)
    at ClientReadableStream.EventEmitter.emit (domain.js:442:20)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at ClientReadableStream.Readable.push (_stream_readable.js:219:10)
    at Object.onReceiveMessage (/Users/jiaruili/git/padplus/node_modules/grpc/src/client_interceptors.js:1258:19)
    at InterceptingListener.recvMessageWithContext (/Users/jiaruili/git/padplus/node_modules/grpc/src/client_interceptors.js:607:19)
    at /Users/jiaruili/git/padplus/node_modules/grpc/src/client_interceptors.js:706:14
(node:15425) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:15425) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by lijiarui** [comment]
No roomId

```
(node:15425) UnhandledPromiseRejectionWarning: Error: has no room for roomId:17301175542@chatroom
    at PadplusManager.<anonymous> (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/src/padplus-manager/padplus-manager.ts:543:11)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/dist/src/padplus-manager/padplus-manager.js:5:58)
(node:15425) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
(node:15425) UnhandledPromiseRejectionWarning: Error: has no room for roomId:868656600@chatroom
    at PadplusManager.<anonymous> (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/src/padplus-manager/padplus-manager.ts:543:11)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/dist/src/padplus-manager/padplus-manager.js:5:58)
(node:15425) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 7)
(node:15425) UnhandledPromiseRejectionWarning: Error: has no room for roomId:868656600@chatroom
    at PadplusManager.<anonymous> (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/src/padplus-manager/padplus-manager.ts:543:11)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/dist/src/padplus-manager/padplus-manager.js:5:58)
(node:15425) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 9)
(node:15425) UnhandledPromiseRejectionWarning: Error: has no room for roomId:17301175542@chatroom
    at PadplusManager.<anonymous> (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/src/padplus-manager/padplus-manager.ts:543:11)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/dist/src/padplus-manager/padplus-manager.js:5:58)
(node:15425) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 11)
(node:15425) UnhandledPromiseRejectionWarning: Error: has no room for roomId:17301175542@chatroom
    at PadplusManager.<anonymous> (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/src/padplus-manager/padplus-manager.ts:543:11)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/dist/src/padplus-manager/padplus-manager.js:5:58)
(node:15425) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 13)
(node:15425) UnhandledPromiseRejectionWarning: Error: has no room for roomId:17301175542@chatroom
    at PadplusManager.<anonymous> (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/src/padplus-manager/padplus-manager.ts:543:11)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/dist/src/padplus-manager/padplus-manager.js:5:58)
(node:15425) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 15)
(node:15425) UnhandledPromiseRejectionWarning: Error: no inviterId found
    at PuppetPadplus.<anonymous> (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/src/puppet-padplus.ts:500:15)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/dist/src/puppet-padplus.js:5:58)
(node:15425) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 16)
```

**Comment by lijiarui** [comment]
It works when a wechat just have several contacts.

**Comment by lijiarui** [comment]
fix
