### ISSUE TITLE
memory-card always get `undefined123.memory-card.json`

### ISSUE THREAD

**Issue by lijiarui** [botorange/wechaty-puppet-padplus#6]

**Comment by windmemory** [comment]
This is resolved.

**Comment by lijiarui** [comment]
I'm afraid not, I got the following error when trying log in:

### wechaty-puppet-padplus: 0.0.54

error log
```
TypeError: Cannot read property 'uin' of undefined
    at PadplusManager.<anonymous> (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/dist/src/padplus-manager/padplus-manager.js:93:34)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/dist/src/padplus-manager/padplus-manager.js:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:279:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:696:3)
21:38:35 ERR Wechaty start() exception: Cannot read property 'uin' of undefined
Bot error: TypeError: Cannot read property 'uin' of undefined
    at PadplusManager.<anonymous> (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/dist/src/padplus-manager/padplus-manager.js:93:34)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/dist/src/padplus-manager/padplus-manager.js:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:279:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:696:3)
21:38:35 INFO Wechaty <Puppet#0<PuppetPadplus>(lijiarui)> stop() v0.28.3 is stoping ...
21:38:35 WARN Wechaty stop() puppet.stop() exception: Method not implemented.
```

**Comment by lijiarui** [comment]
fix
