### ISSUE TITLE
room.avatar() is not supported yet?

### ISSUE THREAD

**Issue by zhongshanb** [botorange/wechaty-puppet-padplus#67]
I am using padplus with version 0.0.141, calling the method room.avatar() in my code
```js
const topic = await room.topic();
const roomFile = await room.avatar()
const roomName = filePath + '/avatar/' + room.id + '.jpg'
const roomAvatar = './avatar/' + room.id + '.jpg'
await roomFile.toFile(roomName, true)
```
result in the following Error, so I guess in padplus room.avatar() is not support yet.

```shell
(node:2879) UnhandledPromiseRejectionWarning: Error: Method not implemented.
    at PuppetPadplus.roomAvatar (/opt/nodejs/demos/node_modules/wechaty-puppet-padplus/dist/src/puppet-padplus.js:953:15)
    at AnotherOriginalClass.<anonymous> (/opt/nodejs/demos/node_modules/wechaty/dist/src/user/room.js:968:32)
    at Generator.next (<anonymous>)
    at /opt/nodejs/demos/node_modules/wechaty/dist/src/user/room.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/opt/nodejs/demos/node_modules/wechaty/dist/src/user/room.js:3:12)
    at AnotherOriginalClass.avatar (/opt/nodejs/demos/node_modules/wechaty/dist/src/user/room.js:966:16)
    at Wechaty.onMessage (/opt/nodejs/demos/wechaty-padpro-bot.js:204:32)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:2879) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:2879) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Please confirm if room.avatar() was supported or not, or if you are planning to support the method, Thank u!

**Comment by su-chang** [comment]
Resolved already, please check it and close this issue.

**Comment by zhongshanb** [comment]
room.avatar() is ok now! This issue is closed
