### ISSUE TITLE
No roomId after login

### ISSUE THREAD

**Issue by lijiarui** [botorange/wechaty-puppet-padplus#7]
No roomId

```
(node:15425) UnhandledPromiseRejectionWarning: Error: has no room for roomId:17301175542@chatroom
    at PadplusManager.<anonymous> (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/src/padplus-manager/padplus-manager.ts:543:11)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/dist/src/padplus-manager/padplus-manager.js:5:58)
(node:15425) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
(node:15425) UnhandledPromiseRejectionWarning: Error: has no room for roomId:868656600@chatroom
    at PadplusManager.<anonymous> (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/src/padplus-manager/padplus-manager.ts:543:11)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/dist/src/padplus-manager/padplus-manager.js:5:58)
(node:15425) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 7)
(node:15425) UnhandledPromiseRejectionWarning: Error: has no room for roomId:868656600@chatroom
    at PadplusManager.<anonymous> (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/src/padplus-manager/padplus-manager.ts:543:11)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/dist/src/padplus-manager/padplus-manager.js:5:58)
(node:15425) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 9)
(node:15425) UnhandledPromiseRejectionWarning: Error: has no room for roomId:17301175542@chatroom
    at PadplusManager.<anonymous> (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/src/padplus-manager/padplus-manager.ts:543:11)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/dist/src/padplus-manager/padplus-manager.js:5:58)
(node:15425) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 11)
(node:15425) UnhandledPromiseRejectionWarning: Error: has no room for roomId:17301175542@chatroom
    at PadplusManager.<anonymous> (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/src/padplus-manager/padplus-manager.ts:543:11)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/dist/src/padplus-manager/padplus-manager.js:5:58)
(node:15425) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 13)
(node:15425) UnhandledPromiseRejectionWarning: Error: has no room for roomId:17301175542@chatroom
    at PadplusManager.<anonymous> (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/src/padplus-manager/padplus-manager.ts:543:11)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/dist/src/padplus-manager/padplus-manager.js:5:58)
(node:15425) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 15)
(node:15425) UnhandledPromiseRejectionWarning: Error: no inviterId found
    at PuppetPadplus.<anonymous> (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/src/puppet-padplus.ts:500:15)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/dist/src/puppet-padplus.js:5:58)
(node:15425) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 16)
```

**Comment by lijiarui** [comment]
fix
