### ISSUE TITLE
bad rs block 

### ISSUE THREAD

**Issue by gytai** [botorange/wechaty-puppet-padplus#74]
18:32:01 INFO Wechaty <Puppet#0<PuppetPadplus>()>(micro-todo-bot) start() v0.29.5 is starting...
18:32:02 ERR Wechaty addListenerFunction(scan) listener exception: Error: bad rs block @ typeNumber:1/errorCorrectLevel:undefined
(node:23726) UnhandledPromiseRejectionWarning: Error: bad rs block @ typeNumber:1/errorCorrectLevel:undefined
    at Function.QRRSBlock.getRSBlocks (/www/wwwroot/bot/node_modules/qrcode-terminal/vendor/QRCode/QRRSBlock.js:261:9)
    at QRCode.make (/www/wwwroot/bot/node_modules/qrcode-terminal/vendor/QRCode/index.js:58:30)
    at generate (/www/wwwroot/bot/node_modules/qrcode-terminal/lib/main.js:35:16)
    at Wechaty.<anonymous> (/www/wwwroot/bot/server.js:29:6)
    at Wechaty.on.args (/www/wwwroot/bot/node_modules/wechaty/src/wechaty.ts:550:18)
    at Wechaty.emit (events.js:189:13)
    at Wechaty.EventEmitter.emit (domain.js:441:20)
    at Wechaty.emit (/www/wwwroot/bot/node_modules/wechaty/src/wechaty.ts:314:18)
    at Wechaty.<anonymous> (/www/wwwroot/bot/node_modules/wechaty/src/wechaty.ts:735:18)
    at Generator.next (<anonymous>)
    at /www/wwwroot/bot/node_modules/wechaty/dist/src/wechaty.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/www/wwwroot/bot/node_modules/wechaty/dist/src/wechaty.js:3:12)
    at PuppetPadplus.puppet.on (/www/wwwroot/bot/node_modules/wechaty/src/wechaty.ts:734:60)
    at PuppetPadplus.emit (events.js:189:13)
    at PuppetPadplus.EventEmitter.emit (domain.js:441:20)
    at PuppetPadplus.emit (/www/wwwroot/bot/node_modules/wechaty-puppet/src/puppet.ts:282:18)
    at PuppetPadplus.<anonymous> (/www/wwwroot/bot/node_modules/wechaty-puppet-padplus/src/puppet-padplus.ts:83:12)
    at Generator.next (<anonymous>)
    at /www/wwwroot/bot/node_modules/wechaty-puppet-padplus/dist/src/puppet-padplus.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/www/wwwroot/bot/node_modules/wechaty-puppet-padplus/dist/src/puppet-padplus.js:4:12)
    at PadplusManager.manager.on (/www/wwwroot/bot/node_modules/wechaty-puppet-padplus/src/puppet-padplus.ts:81:66)
    at PadplusManager.on.args (/www/wwwroot/bot/node_modules/wechaty-puppet-padplus/src/padplus-manager/padplus-manager.ts:183:18)
    at PadplusManager.emit (events.js:189:13)
    at PadplusManager.EventEmitter.emit (domain.js:441:20)
    at PadplusManager.emit (/www/wwwroot/bot/node_modules/wechaty-puppet-padplus/src/padplus-manager/padplus-manager.ts:164:18)
    at PadplusManager.<anonymous> (/www/wwwroot/bot/node_modules/wechaty-puppet-padplus/src/padplus-manager/padplus-manager.ts:360:18)
    at Generator.next (<anonymous>)
    at fulfilled (/www/wwwroot/bot/node_modules/wechaty-puppet-padplus/dist/src/padplus-manager/padplus-manager.js:5:58)
(node:23726) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:23726) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code

**Comment by gytai** [comment]
跑例子代码 出现以上问题
