### ISSUE TITLE
Cannot get qrcode

### ISSUE THREAD

**Issue by lijiarui** [botorange/wechaty-puppet-padplus#8]
error message

```
➜  padplus ts-node test.ts

18:14:08 INFO Wechaty <Puppet#0<PuppetPadplus>()>(lijiarui) start() v0.28.3 is starting...

Error: Can not get data from Transmit Server
    at GrpcGateway.<anonymous> (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/src/server-manager/grpc-gateway.ts:138:13)
    at Generator.throw (<anonymous>)
    at rejected (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/dist/src/server-manager/grpc-gateway.js:6:65)
18:14:28 ERR Wechaty start() exception: Can not get data from Transmit Server
(node:17402) UnhandledPromiseRejectionWarning: Error: Can not get data from Transmit Server
    at GrpcGateway.<anonymous> (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/src/server-manager/grpc-gateway.ts:138:13)
    at Generator.throw (<anonymous>)
    at rejected (/Users/jiaruili/git/padplus/node_modules/wechaty-puppet-padplus/dist/src/server-manager/grpc-gateway.js:6:65)
(node:17402) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:17402) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
18:14:28 ERR GRPC_GATEWAY Error: 14 UNAVAILABLE: failed to connect to all addresses
    at Object.exports.createStatusError (/Users/jiaruili/git/padplus/node_modules/grpc/src/common.js:91:15)
    at ClientReadableStream._emitStatusIfDone (/Users/jiaruili/git/padplus/node_modules/grpc/src/client.js:233:26)
    at ClientReadableStream._receiveStatus (/Users/jiaruili/git/padplus/node_modules/grpc/src/client.js:211:8)
    at Object.onReceiveStatus (/Users/jiaruili/git/padplus/node_modules/grpc/src/client_interceptors.js:1272:15)
    at InterceptingListener._callNext (/Users/jiaruili/git/padplus/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/Users/jiaruili/git/padplus/node_modules/grpc/src/client_interceptors.js:618:8)
    at /Users/jiaruili/git/padplus/node_modules/grpc/src/client_interceptors.js:1029:24

```

**Comment by lijiarui** [comment]
fix
